spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

server:
  port: 9090

logging:
    file:
      path: src/logs/

paths:
  report-storage-path: "/home/alexei/Documents/TMP/FsaReports"
  employee-storage-path: "/home/alexei/dev/employee.json"
  arshin-vri-uri: "https://fgis.gost.ru/fundmetrology/eapi/vri?"

organization:
  sign:
  title:
